version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: stub_requests
      POSTGRES_PASSWORD: stub_requests
      POSTGRES_DB: stub_requests
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    image: ghcr.io/ilnyrnazargulov/stub-service:latest
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stub_requests
      SPRING_DATASOURCE_USERNAME: stub_requests
      SPRING_DATASOURCE_PASSWORD: stub_requests

volumes:
  postgres-data: