global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093
scrape_configs:
#  - job_name: prometheus
#    static_configs:
#      - targets:
#          - prometheus:9090
  - job_name: app
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - app:8080
#  - job_name: node
#    static_configs:
#      - targets:
#          - node-exporter:9100