name: publish

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run the Maven verify phase
        run: mvn clean package
      - name: Login
        run: |
          echo ${{ secrets.GHCR_PASSWORD }} | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Build and Publish
        run: |
          docker build . --tag ${{ secrets.GHCR_USERNAME }}/${{vars.IMAGE_NAME}}
          docker push ${{ secrets.GHCR_USERNAME }}/${{vars.IMAGE_NAME}}

  deploy:
    runs-on: self-hosted
    needs: publish
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Login
        run: echo ${{ secrets.GHCR_PASSWORD }} | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Pull image
        run: docker-compose pull
      - name: docker-compose
        run: docker-compose up --force-recreate --build -d